def greet(l):
    return {'czech':'Vitejte',
            'danish':'Velkomst',
            'dutch':'Welkom',
            'estonian':'Tere tulemast',
            'finnish':'Tervetuloa',
            'flemish':'Welgekomen',
            'french':'Bienvenue',
            'german':'Willkommen',
            'irish':'Failte',
            'italian':'Benvenuto',
            'latvian':'Gaidits',
            'lithuanian':'Laukiamas',
            'polish':'Witamy',
            'spanish':'Bienvenido',
            'swedish':'Valkommen',
            'welsh':'Croeso'}.get(l,'Welcome')
